#spring.datasource.url=jdbc:h2:mem:testdb
#
#spring.datasource.username=sa
#spring.datasource.password=
#
#spring.h2.console.enabled=true
#spring.h2.console.path=/h2-console
#
#
spring.application.name=Wishlist
spring.profiles.active=dev

spring.sql.init.mode=always

spring.devtools.restart.enabled=true
spring.thymeleaf.cache=false